# fly.toml app configuration file generated for backend-wandering-river-6835 on 2025-01-20T09:38:40+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-wandering-river-6835'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[processes]
  app = "python -m uvicorn app.main:create_app --host 0.0.0.0 --port 80"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="sqlite_data"
  destination="/mnt/sqlite_data"